model_list:
    # GEMINI : https://aistudio.google.com/apikey
    - model_name: Gemini Flash Lite 2.0
      litellm_params:
        model: gemini/gemini-2.0-flash-lite
        api_key: os.environ/GEMINI_API_KEY
        rpm: 10
        tpm: 100000
        drop_params: true # Just drop_params when calling specific models
        modify_params: true # to solve the problem with cline plugin in vscode
  
    ## GEMINI's text embedding
    - model_name: gemini/text-embedding-004
      litellm_params:
        model: gemini/text-embedding-004
        api_key: os.environ/GEMINI_API_KEY
        rpm: 10
        tpm: 100000
        drop_params: true # Just drop_params when calling specific models


    # OpenAI : https://platform.openai.com/api-keys
    - model_name: gpt-4o-mini
      litellm_params:
        model: openai/gpt-4o-mini
        api_key: os.environ/OPENAI_API_KEY
        drop_params: true
    
    - model_name: gpt-4.1-nano
      litellm_params:
        model: openai/gpt-4.1-nano
        api_key: os.environ/OPENAI_API_KEY
        drop_params: true


    # # Github Models : https://github.com/marketplace/models
    # - model_name: github/gpt-4o-mini
    #   litellm_params:
    #     model: github/gpt-4o-mini
    #     api_key: os.environ/GITHUB_API_KEY
    #     drop_params: true
  
    # # AWS Bedrock : https://aws.amazon.com/bedrock/
    # - model_name: bedrock/*
    #   litellm_params:
    #     model: bedrock/*
    #     aws_region_name: os.environ/AWS_REGION_NAME
    #     aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
    #     aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
    #     drop_params: true
    #     modify_params: true
  

    # Openrouter : https://openrouter.ai/settings/keys
    - model_name: openrouter/*
      litellm_params:
        model: openrouter/*
        api_key: os.environ/OPENROUTER_API_KEY


    # GROQ CLOUD : https://console.groq.com/keys
    # - model_name: groq/*
    #   litellm_params:
    #     model: groq/*
    #     api_base: https://api.groq.com/openai/v1
    #     api_key: os.environ/GROQ_API_KEY
    #     drop_params: True


general_settings:
    forward_openai_org_id: true

litellm_settings:
    enable_json_schema_validation: True