model_list:
    # GEMINI : https://aistudio.google.com/apikey
    - model_name: gemini-2.0-flash-lite
      litellm_params:
        model: gemini/gemini-2.0-flash-lite
        api_key: os.environ/GEMINI_API_KEY
        rpm: 10
        tpm: 100000
        drop_params: true # Just drop_params when calling specific models
        modify_params: true
  
    ## GEMINI's text embedding
    - model_name: gemini/text-embedding-004
      litellm_params:
        model: gemini/text-embedding-004
        api_key: os.environ/GEMINI_API_KEY
        rpm: 10
        tpm: 100000
        drop_params: true # Just drop_params when calling specific models


    # OpenAI : https://platform.openai.com/api-keys
    - model_name: gpt-4o-mini
      litellm_params:
        model: openai/gpt-4o-mini
        api_key: os.environ/OPENAI_API_KEY
        drop_params: true
    
    - model_name: gpt-4.1-nano
      litellm_params:
        model: openai/gpt-4.1-nano
        api_key: os.environ/OPENAI_API_KEY
        drop_params: true

    # Openrouter : https://openrouter.ai/settings/keys
    - model_name: fake-gpt-command
      litellm_params:
        model: openrouter/cohere/command-r7b-12-2024
        api_key: os.environ/OPENROUTER_API_KEY

    - model_name: deepseek-chat-v3
      litellm_params:
        model: openrouter/deepseek/deepseek-chat-v3
        api_key: os.environ/OPENROUTER_API_KEY

    ## Other services example
    # GROQ CLOUD : https://console.groq.com/keys
    # - model_name: groq/*
    #   litellm_params:
    #     model: groq/*
    #     api_base: https://api.groq.com/openai/v1
    #     api_key: os.environ/GROQ_API_KEY
    #     drop_params: True

router_settings:
  fallbacks: [{"gpt-4.1-nano": ["gpt-4o-mini"]}, {"gemini/gemini-2.0-flash-lite": ["gpt-4.1-nano"]}]

general_settings:
    forward_openai_org_id: true

litellm_settings:
    enable_json_schema_validation: True